"""Base class for self-improving Canopy bots"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from typing import List, Dict, Optional
import logging


@dataclass
class Task:
    """A task generated by a bot"""

    id: str
    bot_id: str
    title: str
    description: str
    priority: float  # 0.0-1.0
    context: Dict  # Additional context for execution
    created_at: datetime
    deadline: Optional[datetime] = None


@dataclass
class TaskOutcome:
    """Result of executing a task"""

    task: Task
    success: bool
    output: str
    tools_used: List[str]
    duration_seconds: float
    errors: List[str]
    completed_at: datetime


@dataclass
class Reflection:
    """Self-reflection after task completion"""

    task_id: str
    bot_id: str
    what_worked: List[str]
    what_failed: List[str]
    corrections: List[str]  # Patterns to remember
    insights: List[str]  # Strategic learnings
    created_at: datetime


class CanopyBot(ABC):
    """Base class for self-improving Canopy bots"""

    def __init__(self, bot_id: str, name: str, role: str, memory_manager):
        self.bot_id = bot_id
        self.name = name
        self.role = role
        self.memory = memory_manager
        self.logger = logging.getLogger(f"canopy.{bot_id}")

    @abstractmethod
    def generate_tasks(self, context: Dict) -> List[Task]:
        """Generate tasks based on current context

        Context may include:
        - calendar_events: Upcoming events
        - recent_messages: Recent Telegram messages
        - current_time: Current datetime
        - weather: Current weather
        - memory_patterns: Active HOT/WARM patterns

        Returns list of Tasks with priorities
        """
        pass

    @abstractmethod
    def execute_task(self, task: Task) -> TaskOutcome:
        """Execute a task using available tools

        Should:
        1. Load relevant memory patterns
        2. Use MCP tools to complete task
        3. Return outcome with details
        """
        pass

    def reflect_on_task(self, outcome: TaskOutcome) -> Reflection:
        """Self-reflection after task completion

        Analyzes:
        - Did task achieve intent?
        - What went well? What failed?
        - What patterns should be remembered?
        - What insights were gained?
        """
        reflection = Reflection(
            task_id=outcome.task.id,
            bot_id=self.bot_id,
            what_worked=[],
            what_failed=[],
            corrections=[],
            insights=[],
            created_at=datetime.now(),
        )

        # Analyze outcome
        if outcome.success:
            reflection.what_worked.append(
                f"Task completed in {outcome.duration_seconds:.1f}s"
            )
            if outcome.tools_used:
                reflection.what_worked.append(
                    f"Used tools: {', '.join(outcome.tools_used)}"
                )
        else:
            reflection.what_failed.append("Task did not complete successfully")
            reflection.what_failed.extend(outcome.errors)

        # Extract patterns (subclass should override to add domain-specific patterns)
        self._extract_patterns(outcome, reflection)

        # Store corrections in memory
        for correction in reflection.corrections:
            self.memory.add_pattern(
                category="correction",
                content=correction,
                context=f"Task: {outcome.task.title}",
                source=f"reflection:{outcome.task.id}",
                metadata={"bot": self.bot_id, "task_id": outcome.task.id},
            )

        # Store insights
        for insight in reflection.insights:
            self.memory.add_pattern(
                category="insight",
                content=insight,
                context=f"Task: {outcome.task.title}",
                source=f"reflection:{outcome.task.id}",
                tier="warm",  # Insights start in WARM
                metadata={"bot": self.bot_id, "task_id": outcome.task.id},
            )

        return reflection

    def _extract_patterns(self, outcome: TaskOutcome, reflection: Reflection):
        """Extract learnable patterns from outcome (override in subclass)"""
        # Base implementation - subclasses add domain-specific pattern extraction
        if not outcome.success and outcome.errors:
            reflection.corrections.append(
                f"Avoid approach that led to: {outcome.errors[0]}"
            )

    def get_active_memory(self) -> List[str]:
        """Get active HOT+WARM patterns as strings for context injection"""
        patterns = self.memory.get_active_patterns(include_hot=True, include_warm=True)
        return [
            f"{p.category.upper()}: {p.content} (Context: {p.context})"
            for p in patterns
        ]

    def format_telegram_message(self, content: str) -> str:
        """Format message for Telegram with bot identity"""
        return f"[{self.name}] {content}"
